### ISSUE TITLE
On clicking inside the sidebar, sidebar should not get closed

### ISSUE THREAD

**Issue by mbj36** [mbj36/vue-burger-menu#4]

**Comment by Mobeidat** [comment]
Can we have this very soon

**Comment by mbj36** [comment]
@Mobeidat I will have time to look into this weekend and hopefully release the fix

I am also happy to accept a PRif you would like to fix

**Comment by macksfield** [comment]
I was just looking into this issue!

Being able to pass a callback function that would determine if the menu closes would be ideal. Or a passed boolean that turns off the auto-close.

It's essentially this function that is causing it to close on click:
```
    documentClick: function documentClick(e) {
      var element = document.querySelector('.bm-burger-button');
      var target = e.target;

      if (element !== target && !element.contains(target)) {
        this.closeMenu();
      }
    }
```

**Comment by Mobeidat** [comment]
Any updates on this?!

**Comment by mbj36** [comment]
@Mobeidat Fixed this in v1.0.3 :)

**Comment by edum18** [comment]
I'm having this issue on v1.0.8. Clicking on a div inside the bar, closes it.

**Comment by mbj36** [comment]
@edum18 I need more info...what you mean `clicking on a div inside the bar` ?

**Comment by RomkaLTU** [comment]
Indeed it's not fixed. Clicking on div or anything else inside off-canvas menu closes it. We talking about slot content here...

**Comment by EggIt** [comment]
I'm on v2.0.2 and i am having the same issue, menu closing upon click on a menu item.

As follow my analysis about the `documentClick` method:

- `element` evaluates to the burgerButton
- The if statement checks if the target element is not contained in the burgerButton
- By checking the DOM the burgerButton is a sibling of the menu and not its parent, so the if always evaluates to true which automatically closes the menu:
```html
<div data-v-9143b462="" data-v-26c5b5fd="" nooverlay="" class="menu-bg" isopen="true">
  <div>
    <div class="bm-menu" style="width: 300px;">
      <nav class="bm-item-list">....</nav>
      <span class="bm-cross-button cross-style"></span>
    </div>
    <div class="bm-burger-button">...</div>
  </div>
</div>
```

Issue fixed by looking up targetElement from parentElement and not from burgetButtonElement:
```javascript
  if (... && !element.parentElement.contains(target) && ...)
```

Please PR this and release it.



```javascript
      if ( ... && !element.parentElement.contains(target) && ... )
```

this way as long as we're clicking inside the parent div of both burgetButton and bmMenu we're not closing the menu.
