### ISSUE TITLE
Close button doesn;t adjust with width size

### ISSUE THREAD

**Issue by mbj36** [mbj36/vue-burger-menu#49]
Seems like close button has fixed position. Need to be relative and should always appear at the appropriate position.

If you increase/decrease the width of the Menu, it gets out of the correct position

**Comment by GeorgeFlorian** [comment]
Was this fixed ? Because whenever I change the width of the menu from the default 400px, the cross remains fixed with `right: 250px` and nothing works to move it somewhere else.

![Screenshot from 2020-10-30 23-41-48](https://user-images.githubusercontent.com/39895513/97759342-82520100-1b09-11eb-9ce9-7805402d7b3a.png)

How do you move it ?
